<a href="https://colab.research.google.com/github/sapnasingh4852-source/python-DATA-science/blob/main/lec06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

dct = {
    'name': ['tom', 'nick','krish','jack'],
    'age' : [ 20,21,19,18],
    'roll': [1,2,3,4]

    }

df = pd.DataFrame(dct,index = ['a','b','c','d'])
display(df)

    name  age  roll
a    tom   20     1
b   nick   21     2
c  krish   19     3
d   jack   18     4

In [5]:
df = pd.read_csv('student_data.csv')
df.head(3)


df.shape

(10000, 8)

In [6]:
df = pd.read_csv('student_data.csv')
df.tail(3)


df.index

RangeIndex(start=0, stop=10000, step=1)

In [7]:
df = pd.read_csv('student_data.csv')
df.tail(3)


df.index
df.iloc[0:5]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [10]:
df = pd.read_csv('student_data.csv')
df[df["assignments_completed"]>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [13]:
df = pd.read_csv('student_data.csv')
df.sort_index()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [14]:
df = pd.read_csv('student_data.csv')
df.dropna()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [15]:
df = pd.read_csv('student_data.csv')
df.isnull()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False

In [16]:
df = pd.read_csv('student_data.csv')
df.notnull()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
9995,True,True,True,True,True,True,True,True
9996,True,True,True,True,True,True,True,True
9997,True,True,True,True,True,True,True,True
9998,True,True,True,True,True,True,True,True
9999,True,True,True,True,True,True,True,True

In [23]:
df = pd.read_csv('student_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB